server:
  port: 8888
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-request-size: 4096MB
      max-file-size: 4096MB
      file-size-threshold: 0B
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/dormitory?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456789
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  # redis配置
  redis:
    #    url: redis://123456@${remote-ip}:46379
    #    username: root
    #    host: 192.168.80.120
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8
    #    username: root
    password: qwe123
    host: 192.168.80.120

# mybatis-plus
mybatis-plus:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/**/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

# 验证码配置
captcha:
  #  验证码类型配置
  code-type: ARITHMETIC
  #  登录图形验证码有效时间/分钟
  expiration: 2
  #  验证码高度
  width: 111
  #  验证码宽度
  heigth: 36
  # 内容长度
  length: 2
  # 字体名称，为空则使用默认字体
  font-name:
  # 字体大小
  font-size: 25

# minio
minio:
  endpoint: ${remote-ip}
  port: 9000
  access-key: admin
  secret-key: 123456789
  secure: false
  bucket-name: dormitory-bucket



remote-ip: 192.168.80.120